version: '3.8'

services:
  web:
    build: 
      context: .
    command: gunicorn --bind 0.0.0.0:5005 applic:flaskAppInstance
    expose:
      - 5005
    env_file:
      - ./.env.prod
      
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web